"""add skill column

Revision ID: 11837245014c
Revises: 280b4b3b153f
Create Date: 2023-07-29 15:30:54.041556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11837245014c'
down_revision = '280b4b3b153f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
