"""add city and state column to user table

Revision ID: 1d61b92c8b70
Revises: 1e979277f87e
Create Date: 2023-08-05 11:23:50.703954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d61b92c8b70'
down_revision = '1e979277f87e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city', sa.String(length=32), nullable=False))
    op.add_column('user', sa.Column('state', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'state')
    op.drop_column('user', 'city')
    # ### end Alembic commands ###
