"""add address column to user

Revision ID: 1e979277f87e
Revises: cb6d0e82358c
Create Date: 2023-08-05 10:47:50.769225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e979277f87e'
down_revision = 'cb6d0e82358c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('addr', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'addr')
    # ### end Alembic commands ###
