"""remove password field

Revision ID: 23022734de2c
Revises: 6cd9e7194b64
Create Date: 2023-08-19 14:52:04.526004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23022734de2c'
down_revision = '6cd9e7194b64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
