"""add skill column

Revision ID: 280b4b3b153f
Revises: f822dd112df9
Create Date: 2023-07-29 15:26:58.804062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280b4b3b153f'
down_revision = 'f822dd112df9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
