"""add column English proficiency and last education

Revision ID: 3ee0fdc9f313
Revises: 23022734de2c
Create Date: 2023-08-19 14:55:06.259932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee0fdc9f313'
down_revision = '23022734de2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
