"""add skill column

Revision ID: 482867e9f89c
Revises: 11837245014c
Create Date: 2023-07-29 15:36:33.299677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482867e9f89c'
down_revision = '11837245014c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('skill', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'skill')
    # ### end Alembic commands ###
