"""add column English proficiency and last education

Revision ID: 4c1918129ea7
Revises: 4cd67420ccf1
Create Date: 2023-08-19 14:58:44.582927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c1918129ea7'
down_revision = '4cd67420ccf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('english_proficiency', sa.String(length=32), nullable=False))
    op.add_column('user', sa.Column('last_education', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_education')
    op.drop_column('user', 'english_proficiency')
    # ### end Alembic commands ###
