"""add column

Revision ID: 4cd67420ccf1
Revises: a22745581478
Create Date: 2023-08-19 14:56:53.512489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd67420ccf1'
down_revision = 'a22745581478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
