"""add document id and document table

Revision ID: 61f840b6dd95
Revises: 482867e9f89c
Create Date: 2023-07-29 16:12:50.380265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61f840b6dd95'
down_revision = '482867e9f89c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('document_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'document_id')
    # ### end Alembic commands ###
