"""add column English proficiency and last education

Revision ID: 6cd9e7194b64
Revises: 930af823e807
Create Date: 2023-08-19 14:38:13.232160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd9e7194b64'
down_revision = '930af823e807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
