"""remove password field

Revision ID: 930af823e807
Revises: 1d61b92c8b70
Create Date: 2023-08-19 12:56:29.497335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930af823e807'
down_revision = '1d61b92c8b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.drop_column('user', 'forgot_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('forgot_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
