"""add column English proficiency and last education

Revision ID: a22745581478
Revises: 3ee0fdc9f313
Create Date: 2023-08-19 14:56:28.147601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22745581478'
down_revision = '3ee0fdc9f313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
