"""make optional actual file path

Revision ID: cb6d0e82358c
Revises: 569156554395
Create Date: 2023-07-29 16:30:28.750180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb6d0e82358c'
down_revision = '569156554395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
